export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';

export const ORDER_START_REDIRECT = 'ORDER_START_REDIRECT';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_SUBMIT = 'ORDER_SUBMIT';
export const ORDER_ERROR = 'ORDER_ERROR';
