export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ASYNC_FETCH_INGREDIENTS = 'ASYNC_FETCH_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';
